import discord
from discord.ext import commands
from discord import app_commands
import datastore
import fx_helper
from datastore import BOT_ADMINISTRATIVE

class Join_msg(commands.Cog):
    def __init__(self, bot):
        self.bot = bot

    @commands.Cog.listener()
    async def on_member_join(self, member: discord.Member):
        mode = datastore.JOIN_MESSAGE_MODE

        if mode == "disabled":
            return

        try:
            if mode == "default":
                embed = discord.Embed(
                    title="Welcome to the Server!",
                    description = (
    f"Hello {member.mention},\n"
    f"Welcome to the {member.guild.name} server.\n\n"
    f"It is requested that you select the `show all channels` buttons from the drop down menu to get full access to the utilities of the server."),
                    color=discord.Color.blue()
                    )
                embed.set_thumbnail(url=member.guild.icon.url if member.guild.icon else None)
                embed.set_image(url=datastore.joining_gif)
                embed.set_footer(text="Message auto-generated by Ingenuity Bot")
                await member.send(embed=embed)

            elif mode == "custom":
                embed = discord.Embed(
                    title="Welcome to the Server!",
                    description= datastore.CUSTOM_JOIN_MESSAGE,
                    color=discord.Color.blue()
                )
                embed.set_thumbnail(url=member.guild.icon.url if member.guild.icon else None)
                embed.set_image(url=datastore.joining_gif)
                embed.set_footer(text="Message auto-generated by Ingenuity Bot")
                await member.send(embed=embed)

            await fx_helper.send_log(member.guild, f"Sent a welcome DM to {member.name}")

        except discord.Forbidden:
            await fx_helper.send_log(member.guild, f"Failed to send a DM to {member.name}. DMs might be closed.")

    @app_commands.command(name="toggle_join_message", description="Cycle between welcome message modes (default, custom, disabled).")
    async def toggle_join_message(self, interaction: discord.Interaction):
        if not any(role.name in BOT_ADMINISTRATIVE for role in interaction.user.roles):
            await interaction.response.send_message(
                "🚫 You do not have permission to use this command.", ephemeral=True
            )
            return

        current_mode = datastore.JOIN_MESSAGE_MODE
        modes = ["default", "custom", "disabled"]
        next_index = (modes.index(current_mode) + 1) % len(modes)
        datastore.JOIN_MESSAGE_MODE = modes[next_index]

        await interaction.response.send_message(
            f"✅ Welcome message mode has been set to **{datastore.JOIN_MESSAGE_MODE}**.", ephemeral=True
        )

    @app_commands.command(name="set_custom_join_message", description="Set a custom join message (text only).")
    @app_commands.describe(message="The message to send to new members.")
    async def set_custom_join_message(self, interaction: discord.Interaction, message: str):
        if not any(role.name in BOT_ADMINISTRATIVE for role in interaction.user.roles):
            await interaction.response.send_message("🚫 You do not have permission to use this command.", ephemeral=True)
            return

        datastore.CUSTOM_JOIN_MESSAGE = message
        await interaction.response.send_message("✅ Custom join message updated successfully!", ephemeral=True)

    @app_commands.command(name="test_join_message", description="Send yourself the current welcome message for testing.")
    async def test_join_message(self, interaction: discord.Interaction):
        # if not any(role.name in BOT_ADMINISTRATIVE for role in interaction.user.roles):
        #     await interaction.response.send_message("🚫 You do not have permission to use this command.", ephemeral=True)
        #     return

        mode = datastore.JOIN_MESSAGE_MODE

        try:
            if mode == "disabled":
                await interaction.response.send_message("ℹ️ Join message is currently **disabled**.", ephemeral=True)
                return

            if mode == "default":
                embed = discord.Embed(
                    title="Welcome to the Server!",
                    description=(
    f"Hello {interaction.user.mention},\n"
    f"Welcome to the {interaction.user.guild.name} server.\n\n"
    f"It is requested that you select the `show all channels` buttons from the drop down menu to get full access to the utilities of the server."),
                    color=discord.Color.blue()
                )
                embed.set_thumbnail(url=interaction.guild.icon.url if interaction.guild.icon else None)
                embed.set_image(url=datastore.joining_gif)
                embed.set_footer(text="Message auto-generated by Ingenuity Bot")
                await interaction.user.send(embed=embed)

            elif mode == "custom":
                embed = discord.Embed(
                    title="Welcome to the Server!",
                    description= datastore.CUSTOM_JOIN_MESSAGE,
                    color=discord.Color.blue()
                )
                embed.set_thumbnail(url=interaction.guild.icon.url if interaction.guild.icon else None)
                embed.set_image(url=datastore.joining_gif)
                embed.set_footer(text="Message auto-generated by Ingenuity Bot")
                await interaction.user.send(embed=embed)

            await interaction.response.send_message("✅ Sent the current welcome message to your DMs!", ephemeral=True)

        except discord.Forbidden:
            await interaction.response.send_message("⚠️ Could not send you a DM. Please check your privacy settings.", ephemeral=True)


async def setup(bot):
    await bot.add_cog(Join_msg(bot))
